package:
  name: pear
  version: 0.9.11

source:
  fn: pear-0.9.11.tar.gz
  url: ./pear-src-0.9.11.tar.gz
  sha256: 064b383beba71b7f66ed4da852cad4cc40e480ca52307b6fa7d1393c8219f9f9

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
  host:
    - bzip2 ==1.0.6
    - zlib ==1.2.11
  run:
    - bzip2 ==1.0.6
    - zlib ==1.2.11

test:
  commands:
    - pear --version | grep "PEAR 0.9.11"

about:
  home: http://www.exelixis-lab.org/pear
  license: CC-BY-NC-SA-3.0
  license_file: COPYING
  summary: PEAR is an ultrafast, memory-efficient and highly accurate pair-end read merger
