package:
  name: hivmmer
  version: 0.1.0

source:
  git_url: https://github.com/mhowison/hivmmer
  git_tag: v0.1.0

build:
  script: pip install --no-deps .

requirements:
  build:
    - python
    - biopython
    - numpy
    - pandas
  run:
    - python
    - biopython
    - numpy
    - pandas
    - fastx_toolkit ==0.0.14
    - hmmer ==3.1b2
    - pear ==0.9.11

test:
  commands:
    - hivmmer -h
    - hivmmer-codons -h
    - hivmmer-translate -h

about:
  home: https://github.com/mhowison/hivmmer
  summary: "An alignment and variant-calling pipeline for Illumina deep sequencing of
            HIV-1, based on the probabilistic aligner HMMER."
  license: BSD-like
  license_file: LICENSE
