package:
  name: hmmer
  version: 3.1b2

source:
  fn: hmmer-3.1b2.tar.gz
  url: http://eddylab.org/software/hmmer3/3.1b2/hmmer-3.1b2.tar.gz
  md5: c8c141018bc0ccd7fc37b33f2b945d5f

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - alimask -h 2>&1 | grep Usage > /dev/null

about:
  home: http://hmmer.janelia.org/
  summary: Biosequence analysis using profile hidden Markov models
  license: GPLv3
  license_file: LICENSE
